export const API_URL = {
  conversations: '/conversations',
  dataInterests: '/data-interests',
  gallery: '/gallery',
  galleryPhoto: '/gallery/photos',
  loginByEmail: '/auth/login/email',
  loginByFacebook: '/auth/login/facebook',
  loginByGoogle: '/auth/login/google',
  nearbyUsers: '/users/nearby',
  messages: 'messages',
  myProfile: '/users/profile',
  myGallery: '/gallery/my',
  isExistUser: '/users/exist',
  signInWithPhoneNumber: '/auth/sign-in/phone-number',
  users: '/users',
};
