export const API_URL = {
  conversations: '/conversations',
  dataInterests: '/data-interests',
  gallery: '/gallery',
  loginByEmail: '/auth/login/email',
  loginByFacebook: '/auth/login/facebook',
  loginByGoogle: '/auth/login/google',
  myProfile: '/profile',
  myProfileBasicInfo: '/profile/basic-info',
  myGallery: '/gallery/my',
  photos: '/upload-files/photos',
  usersSwipe: '/users/swipe',
  signInWithPhoneNumber: '/auth/sign-in/phone-number',
  uploadFiles: '/upload-files',
  users: '/users',
  usersNearby: '/users/nearby',
};
