export const API_URL = {
  conversations: '/conversations',
  // loginByEmail: '/auth/login/email',
  // loginByFacebook: '/auth/login/facebook',
  // loginByGoogle: '/auth/login/google',
  likedMe: '/likes/me',
  likes: '/likes',
  logout: '/auth/logout',
  matches: '/matches',
  messages: '/messages',
  me: '/me',
  myProfileBasicInfo: '/me/basic-info',
  photos: '/media-files/photos',
  usersSwipe: '/users/swipe',
  signInWithPhoneNumber: '/auth/sign-in/phone-number',
  mediaFiles: '/media-files',
  users: '/users',
  usersNearby: '/users/nearby',
  views: '/views',
};
